/**
 * N-400 Civics Questions Data
 * Official 100 questions for the USCIS 2008 Naturalization Test
 *
 * Data Structure:
 * - q: Question text
 * - a: Answer(s) - HTML formatted for display
 */

const questions = [
    { q: "What is the supreme law of the land?", a: "The Constitution" },
    { q: "What does the Constitution do?", a: "• Sets up the government<br>• Defines the government<br>• Protects basic rights of Americans" },
    { q: "The idea of self-government is in the first three words of the Constitution. What are these words?", a: "We the People" },
    { q: "What is an amendment?", a: "• A change to the Constitution<br>• An addition to the Constitution" },
    { q: "What do we call the first ten amendments to the Constitution?", a: "The Bill of Rights" },
    { q: "What is one right or freedom from the First Amendment?", a: "• Speech<br>• Religion<br>• Assembly<br>• Press<br>• Petition the government" },
    { q: "How many amendments does the Constitution have?", a: "Twenty-seven (27)" },
    { q: "What did the Declaration of Independence do?", a: "• Announced our independence from Great Britain<br>• Declared our independence from Great Britain<br>• Said that the United States is free from Great Britain" },
    { q: "What are two rights in the Declaration of Independence?", a: "• Life<br>• Liberty<br>• Pursuit of happiness" },
    { q: "What is freedom of religion?", a: "You can practice any religion, or not practice a religion" },
    { q: "What is the economic system in the United States?", a: "• Capitalist economy<br>• Market economy" },
    { q: "What is the 'rule of law'?", a: "• Everyone must follow the law<br>• Leaders must obey the law<br>• Government must obey the law<br>• No one is above the law" },
    { q: "Name one branch or part of the government.", a: "• Congress<br>• Legislative<br>• President<br>• Executive<br>• The courts<br>• Judicial" },
    { q: "What stops one branch of government from becoming too powerful?", a: "• Checks and balances<br>• Separation of powers" },
    { q: "Who is in charge of the executive branch?", a: "The President" },
    { q: "Who makes federal laws?", a: "• Congress<br>• Senate and House of Representatives<br>• U.S. or national legislature" },
    { q: "What are the two parts of the U.S. Congress?", a: "The Senate and House of Representatives" },
    { q: "How many U.S. Senators are there?", a: "One hundred (100)" },
    { q: "We elect a U.S. Senator for how many years?", a: "Six (6)" },
    { q: "Who is one of your state's U.S. Senators now?", a: "Answers will vary. [Visit uscis.gov/citizenship/find-study-materials for your state's senators]" },
    { q: "The House of Representatives has how many voting members?", a: "Four hundred thirty-five (435)" },
    { q: "We elect a U.S. Representative for how many years?", a: "Two (2)" },
    { q: "Name your U.S. Representative.", a: "Answers will vary. [Visit uscis.gov/citizenship/find-study-materials to find your representative]" },
    { q: "Who does a U.S. Senator represent?", a: "All people of the state" },
    { q: "Why do some states have more Representatives than other states?", a: "• Because of the state's population<br>• Because they have more people<br>• Because some states have more people" },
    { q: "We elect a President for how many years?", a: "Four (4)" },
    { q: "In what month do we vote for President?", a: "November" },
    { q: "What is the name of the President of the United States now?", a: "Donald Trump" },
    { q: "What is the name of the Vice President of the United States now?", a: "J.D. Vance" },
    { q: "If the President can no longer serve, who becomes President?", a: "The Vice President" },
    { q: "If both the President and the Vice President can no longer serve, who becomes President?", a: "The Speaker of the House" },
    { q: "Who is the Commander in Chief of the military?", a: "The President" },
    { q: "Who signs bills to become laws?", a: "The President" },
    { q: "Who vetoes bills?", a: "The President" },
    { q: "What does the President's Cabinet do?", a: "Advises the President" },
    { q: "What are two Cabinet-level positions?", a: "• Secretary of State<br>• Secretary of Defense<br>• Secretary of Treasury<br>• Secretary of Homeland Security<br>• Attorney General<br>• (and others)" },
    { q: "What does the judicial branch do?", a: "• Reviews laws<br>• Explains laws<br>• Resolves disputes<br>• Decides if a law goes against the Constitution" },
    { q: "What is the highest court in the United States?", a: "The Supreme Court" },
    { q: "How many justices are on the Supreme Court?", a: "Nine (9)" },
    { q: "Who is the Chief Justice of the United States now?", a: "John Roberts (John G. Roberts, Jr.)" },
    { q: "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?", a: "• To print money<br>• To declare war<br>• To create an army<br>• To make treaties" },
    { q: "Under our Constitution, some powers belong to the states. What is one power of the states?", a: "• Provide schooling and education<br>• Provide protection (police)<br>• Provide safety (fire departments)<br>• Give a driver's license<br>• Approve zoning and land use" },
    { q: "Who is the Governor of your state now?", a: "Answers will vary. [Michigan residents: Gretchen Whitmer]" },
    { q: "What is the capital of your state?", a: "Answers will vary. [Michigan residents: Lansing]" },
    { q: "What are the two major political parties in the United States?", a: "Democratic and Republican" },
    { q: "What is the political party of the President now?", a: "Republican Party" },
    { q: "What is the name of the Speaker of the House of Representatives now?", a: "Mike Johnson" },
    { q: "There are four amendments to the Constitution about who can vote. Describe one of them.", a: "• Citizens eighteen (18) and older can vote<br>• You don't have to pay to vote<br>• Any citizen can vote (women and men)<br>• A male citizen of any race can vote" },
    { q: "What is one responsibility that is only for United States citizens?", a: "• Serve on a jury<br>• Vote in a federal election" },
    { q: "Name one right only for United States citizens.", a: "• Vote in a federal election<br>• Run for federal office" },
    { q: "What are two rights of everyone living in the United States?", a: "• Freedom of expression<br>• Freedom of speech<br>• Freedom of assembly<br>• Freedom to petition the government<br>• Freedom of religion<br>• The right to bear arms" },
    { q: "What do we show loyalty to when we say the Pledge of Allegiance?", a: "• The United States<br>• The flag" },
    { q: "What is one promise you make when you become a United States citizen?", a: "• Give up loyalty to other countries<br>• Defend the Constitution and laws of the United States<br>• Obey the laws of the United States<br>• Serve in the U.S. military (if needed)<br>• Serve the nation (if needed)<br>• Be loyal to the United States" },
    { q: "How old do citizens have to be to vote for President?", a: "Eighteen (18) and older" },
    { q: "What are two ways that Americans can participate in their democracy?", a: "• Vote<br>• Join a political party<br>• Help with a campaign<br>• Join a civic group<br>• Join a community group<br>• Give an elected official your opinion<br>• Call Senators and Representatives<br>• Run for office<br>• Write to a newspaper" },
    { q: "When is the last day you can send in federal income tax forms?", a: "April 15" },
    { q: "When must all men register for the Selective Service?", a: "• At age eighteen (18)<br>• Between eighteen (18) and twenty-six (26)" },
    { q: "What is one reason colonists came to America?", a: "• Freedom<br>• Political liberty<br>• Religious freedom<br>• Economic opportunity<br>• Practice their religion<br>• Escape persecution" },
    { q: "Who lived in America before the Europeans arrived?", a: "• American Indians<br>• Native Americans" },
    { q: "What group of people was taken to America and sold as slaves?", a: "• Africans<br>• People from Africa" },
    { q: "Why did the colonists fight the British?", a: "• Because of high taxes<br>• Because the British army stayed in their houses<br>• Because they didn't have self-government" },
    { q: "Who wrote the Declaration of Independence?", a: "Thomas Jefferson" },
    { q: "When was the Declaration of Independence adopted?", a: "July 4, 1776" },
    { q: "There were 13 original states. Name three.", a: "• New Hampshire<br>• Massachusetts<br>• Rhode Island<br>• Connecticut<br>• New York<br>• New Jersey<br>• Pennsylvania<br>• Delaware<br>• Maryland<br>• Virginia<br>• North Carolina<br>• South Carolina<br>• Georgia" },
    { q: "What happened at the Constitutional Convention?", a: "• The Constitution was written<br>• The Founding Fathers wrote the Constitution" },
    { q: "When was the Constitution written?", a: "1787" },
    { q: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", a: "• James Madison<br>• Alexander Hamilton<br>• John Jay<br>• Publius" },
    { q: "What is one thing Benjamin Franklin is famous for?", a: "• U.S. diplomat<br>• Oldest member of the Constitutional Convention<br>• First Postmaster General of the United States<br>• Writer of 'Poor Richard's Almanac'<br>• Started the first free libraries" },
    { q: "Who is the 'Father of Our Country'?", a: "George Washington" },
    { q: "Who was the first President?", a: "George Washington" },
    { q: "What territory did the United States buy from France in 1803?", a: "• The Louisiana Territory<br>• Louisiana" },
    { q: "Name one war fought by the United States in the 1800s.", a: "• War of 1812<br>• Mexican-American War<br>• Civil War<br>• Spanish-American War" },
    { q: "Name the U.S. war between the North and the South.", a: "• The Civil War<br>• The War between the States" },
    { q: "Name one problem that led to the Civil War.", a: "• Slavery<br>• Economic reasons<br>• States' rights" },
    { q: "What was one important thing that Abraham Lincoln did?", a: "• Freed the slaves (Emancipation Proclamation)<br>• Saved (or preserved) the Union<br>• Led the United States during the Civil War" },
    { q: "What did the Emancipation Proclamation do?", a: "• Freed the slaves<br>• Freed slaves in the Confederacy<br>• Freed slaves in most Southern states" },
    { q: "What did Susan B. Anthony do?", a: "• Fought for women's rights<br>• Fought for civil rights" },
    { q: "Name one war fought by the United States in the 1900s.", a: "• World War I<br>• World War II<br>• Korean War<br>• Vietnam War<br>• Gulf (Persian Gulf) War" },
    { q: "Who was President during World War I?", a: "Woodrow Wilson" },
    { q: "Who was President during the Great Depression and World War II?", a: "Franklin Roosevelt" },
    { q: "Who did the United States fight in World War II?", a: "Japan, Germany, and Italy" },
    { q: "Before he was President, Eisenhower was a general. What war was he in?", a: "World War II" },
    { q: "During the Cold War, what was the main concern of the United States?", a: "Communism" },
    { q: "What movement tried to end racial discrimination?", a: "Civil rights movement" },
    { q: "What did Martin Luther King, Jr. do?", a: "• Fought for civil rights<br>• Worked for equality for all Americans" },
    { q: "What major event happened on September 11, 2001, in the United States?", a: "Terrorists attacked the United States" },
    { q: "Name one American Indian tribe in the United States.", a: "• Cherokee<br>• Navajo<br>• Sioux<br>• Chippewa<br>• Choctaw<br>• Apache<br>• Iroquois<br>• Creek<br>• Blackfeet<br>• Seminole<br>• (and many others)" },
    { q: "Name one of the two longest rivers in the United States.", a: "• Missouri River<br>• Mississippi River" },
    { q: "What ocean is on the West Coast of the United States?", a: "Pacific Ocean" },
    { q: "What ocean is on the East Coast of the United States?", a: "Atlantic Ocean" },
    { q: "Name one U.S. territory.", a: "• Puerto Rico<br>• U.S. Virgin Islands<br>• American Samoa<br>• Northern Mariana Islands<br>• Guam" },
    { q: "Name one state that borders Canada.", a: "• Maine<br>• New Hampshire<br>• Vermont<br>• New York<br>• Pennsylvania<br>• Ohio<br>• Michigan<br>• Minnesota<br>• North Dakota<br>• Montana<br>• Idaho<br>• Washington<br>• Alaska" },
    { q: "Name one state that borders Mexico.", a: "• California<br>• Arizona<br>• New Mexico<br>• Texas" },
    { q: "What is the capital of the United States?", a: "Washington, D.C." },
    { q: "Where is the Statue of Liberty?", a: "• New York Harbor<br>• Liberty Island<br>• New Jersey<br>• New York" },
    { q: "Why does the flag have 13 stripes?", a: "• Because there were 13 original colonies<br>• Because the stripes represent the original colonies" },
    { q: "Why does the flag have 50 stars?", a: "• Because there is one star for each state<br>• Because each star represents a state<br>• Because there are 50 states" },
    { q: "What is the name of the national anthem?", a: "The Star-Spangled Banner" },
    { q: "When do we celebrate Independence Day?", a: "July 4" },
    { q: "Name two national U.S. holidays.", a: "• New Year's Day<br>• Martin Luther King, Jr. Day<br>• Presidents' Day<br>• Memorial Day<br>• Independence Day<br>• Labor Day<br>• Columbus Day<br>• Veterans Day<br>• Thanksgiving<br>• Christmas" }
];
