/**
 * N-400 Civics Study Sentences
 * Questions and answers rephrased as complete sentences for easier learning
 */

const sentences = [
    // American Government - Principles of American Democracy
    "The supreme law of the land is the Constitution.",
    "The Constitution sets up the government, defines the government, and protects basic rights of Americans.",
    "The first three words of the Constitution are 'We the People'.",
    "An amendment is a change to the Constitution or an addition to the Constitution.",
    "The first ten amendments to the Constitution are called the Bill of Rights.",
    "The First Amendment includes freedom of speech, religion, assembly, press, and the right to petition the government.",
    "The Constitution has twenty-seven (27) amendments.",
    "The Declaration of Independence announced our independence from Great Britain.",
    "Two rights in the Declaration of Independence are life, liberty, and the pursuit of happiness.",
    "Freedom of religion means you can practice any religion, or not practice a religion.",
    "The economic system in the United States is a capitalist economy or market economy.",
    "The 'rule of law' means everyone must follow the law, leaders must obey the law, government must obey the law, and no one is above the law.",

    // System of Government
    "The three branches of government are Congress (legislative), the President (executive), and the courts (judicial).",
    "Checks and balances, or separation of powers, stops one branch of government from becoming too powerful.",
    "The President is in charge of the executive branch.",
    "Congress makes federal laws. Congress includes the Senate and House of Representatives, also called the U.S. or national legislature.",
    "The two parts of the U.S. Congress are the Senate and House of Representatives.",
    "There are one hundred (100) U.S. Senators.",
    "We elect a U.S. Senator for six (6) years.",
    "Michigan's U.S. Senators are Elissa Slotkin and Gary Peters. (Answers vary by state)",
    "The House of Representatives has four hundred thirty-five (435) voting members.",
    "We elect a U.S. Representative for two (2) years.",
    "Your U.S. Representative depends on where you live. (Answers vary by district)",
    "A U.S. Senator represents all people of their state.",
    "Some states have more Representatives than other states because of the state's population - states with more people have more representatives.",
    "We elect a President for four (4) years.",
    "We vote for President in November.",
    "The President of the United States is Donald Trump.",
    "The Vice President of the United States is J.D. Vance.",
    "If the President can no longer serve, the Vice President becomes President.",
    "If both the President and Vice President can no longer serve, the Speaker of the House becomes President.",
    "The Commander in Chief of the military is the President.",
    "The President signs bills to become laws.",
    "The President vetoes bills.",
    "The President's Cabinet advises the President.",
    "Cabinet-level positions include Secretary of State, Secretary of Defense, Secretary of Treasury, Secretary of Homeland Security, and Attorney General, among others.",
    "The judicial branch reviews laws, explains laws, resolves disputes, and decides if a law goes against the Constitution.",
    "The highest court in the United States is the Supreme Court.",
    "There are nine (9) justices on the Supreme Court.",
    "The Chief Justice of the United States is John Roberts (John G. Roberts, Jr.).",
    "One power of the federal government is to print money, declare war, create an army, or make treaties.",
    "One power of the states is to provide schooling and education, provide protection (police), provide safety (fire departments), give driver's licenses, or approve zoning and land use.",
    "The Governor of Michigan is Gretchen Whitmer. (Answers vary by state)",
    "The capital of Michigan is Lansing. (Answers vary by state)",
    "The two major political parties in the United States are Democratic and Republican.",
    "The political party of the President is the Republican Party.",
    "The name of the Speaker of the House of Representatives is Mike Johnson.",

    // Rights and Responsibilities
    "Four amendments about voting rights state that citizens eighteen (18) and older can vote, you don't have to pay to vote, any citizen can vote (women and men), and a male citizen of any race can vote.",
    "Responsibilities that are only for United States citizens include serving on a jury and voting in a federal election.",
    "Rights that are only for United States citizens include voting in a federal election and running for federal office.",
    "Rights of everyone living in the United States include freedom of expression, freedom of speech, freedom of assembly, freedom to petition the government, freedom of religion, and the right to bear arms.",
    "When we say the Pledge of Allegiance, we show loyalty to the United States and the flag.",
    "When you become a United States citizen, you promise to give up loyalty to other countries, defend the Constitution and laws of the United States, obey the laws of the United States, serve in the U.S. military if needed, serve the nation if needed, and be loyal to the United States.",
    "Citizens have to be eighteen (18) and older to vote for President.",
    "Americans can participate in their democracy by voting, joining a political party, helping with a campaign, joining a civic group, joining a community group, giving an elected official their opinion, calling Senators and Representatives, running for office, or writing to a newspaper.",
    "The last day you can send in federal income tax forms is April 15.",
    "All men must register for the Selective Service at age eighteen (18), or between eighteen (18) and twenty-six (26).",

    // American History - Colonial Period and Independence
    "Colonists came to America for freedom, political liberty, religious freedom, economic opportunity, to practice their religion, or to escape persecution.",
    "American Indians, or Native Americans, lived in America before the Europeans arrived.",
    "Africans, or people from Africa, were taken to America and sold as slaves.",
    "The colonists fought the British because of high taxes, because the British army stayed in their houses, or because they didn't have self-government.",
    "Thomas Jefferson wrote the Declaration of Independence.",
    "The Declaration of Independence was adopted on July 4, 1776.",
    "The 13 original states were New Hampshire, Massachusetts, Rhode Island, Connecticut, New York, New Jersey, Pennsylvania, Delaware, Maryland, Virginia, North Carolina, South Carolina, and Georgia.",
    "At the Constitutional Convention, the Constitution was written by the Founding Fathers.",
    "The Constitution was written in 1787.",
    "The Federalist Papers, which supported the passage of the U.S. Constitution, were written by James Madison, Alexander Hamilton, John Jay, or Publius.",
    "Benjamin Franklin is famous for being a U.S. diplomat, the oldest member of the Constitutional Convention, the first Postmaster General of the United States, the writer of 'Poor Richard's Almanac', and starting the first free libraries.",
    "George Washington is the 'Father of Our Country'.",
    "George Washington was the first President.",

    // 1800s
    "The United States bought the Louisiana Territory (or Louisiana) from France in 1803.",
    "Wars fought by the United States in the 1800s include the War of 1812, Mexican-American War, Civil War, and Spanish-American War.",
    "The U.S. war between the North and the South was the Civil War, or the War between the States.",
    "Problems that led to the Civil War include slavery, economic reasons, and states' rights.",
    "Abraham Lincoln freed the slaves (Emancipation Proclamation), saved or preserved the Union, and led the United States during the Civil War.",
    "The Emancipation Proclamation freed the slaves, freed slaves in the Confederacy, or freed slaves in most Southern states.",
    "Susan B. Anthony fought for women's rights and civil rights.",

    // Recent American History and Geography
    "Wars fought by the United States in the 1900s include World War I, World War II, Korean War, Vietnam War, and the Gulf (Persian Gulf) War.",
    "Woodrow Wilson was President during World War I.",
    "Franklin Roosevelt was President during the Great Depression and World War II.",
    "The United States fought Japan, Germany, and Italy in World War II.",
    "Before he was President, Eisenhower was a general in World War II.",
    "During the Cold War, the main concern of the United States was Communism.",
    "The civil rights movement tried to end racial discrimination.",
    "Martin Luther King, Jr. fought for civil rights and worked for equality for all Americans.",
    "On September 11, 2001, terrorists attacked the United States.",
    "American Indian tribes in the United States include Cherokee, Navajo, Sioux, Chippewa, Choctaw, Apache, Iroquois, Creek, Blackfeet, and Seminole, among many others.",
    "The two longest rivers in the United States are the Missouri River and Mississippi River.",
    "The ocean on the West Coast of the United States is the Pacific Ocean.",
    "The ocean on the East Coast of the United States is the Atlantic Ocean.",
    "U.S. territories include Puerto Rico, U.S. Virgin Islands, American Samoa, Northern Mariana Islands, and Guam.",
    "States that border Canada include Maine, New Hampshire, Vermont, New York, Pennsylvania, Ohio, Michigan, Minnesota, North Dakota, Montana, Idaho, Washington, and Alaska.",
    "States that border Mexico include California, Arizona, New Mexico, and Texas.",
    "The capital of the United States is Washington, D.C.",
    "The Statue of Liberty is located in New York Harbor, on Liberty Island, in New Jersey, or in New York.",

    // Symbols and Holidays
    "The flag has 13 stripes because there were 13 original colonies, and the stripes represent the original colonies.",
    "The flag has 50 stars because there is one star for each state - each star represents a state, and there are 50 states.",
    "The name of the national anthem is The Star-Spangled Banner.",
    "We celebrate Independence Day on July 4.",
    "National U.S. holidays include New Year's Day, Martin Luther King Jr. Day, Presidents' Day, Memorial Day, Independence Day, Labor Day, Columbus Day, Veterans Day, Thanksgiving, and Christmas."
];
